#!mast .ruby .yardopts bin demo eg lib man qed spec test [A-Z]*.*
.yardopts
demo/01_basic.md
demo/02_general.md
demo/03_battery.md
demo/05_include.md
demo/06_extend.md
demo/07_namespaces.md
demo/08_dynamic.md
demo/09_nested.md
demo/applique/setup.rb
lib/paramix/version.rb
lib/paramix.rb
LICENSE.txt
HISTORY.md
README.md
DEMO.md
